### ISSUE TITLE
Install/Update not working anymore

### ISSUE THREAD

**Issue by abhigit23** [roddhjav/apparmor.d#99] opened 2023-01-14 11:27 UTC
After updating the system pacman or yay giving errors on app update/install.

    $ sudo pacman -S pdftk
```resolving dependencies...
looking for conflicting packages...

Packages (3) bcprov-1.72-1  java-commons-lang-3.12.0-1  pdftk-3.3.3-2

Total Installed Size:  10.09 MiB

:: Proceed with installation? [Y/n] y 
(3/3) checking keys in keyring                               [################################] 100%
(3/3) checking package integrity                             [################################] 100%
(3/3) loading package files                                  [################################] 100%
(3/3) checking for file conflicts                            [################################] 100%
(3/3) checking available disk space                          [################################] 100%
:: Running pre-transaction hooks...
(1/1) Performing snapper pre snapshots for the following configurations...
error: could not get current working directory
call to execv failed (Permission denied)
error: command failed to execute correctly
error: failed to commit transaction (failed to run transaction hooks)
Errors occurred, no packages were upgraded.
```

    $ sudo aa-log pacman
```
ALLOWED pacman exec /usr/share/libalpm/scripts/snap-pac info="profile transition not found" comm=pacman requested_mask=x denied_mask=x error=-13
```

[full output of aa-log is here](https://privatebin.net/?28b4999fba3d935f#3wK7sCx9x8Q8pCyDNSLQwnie6taieQFuuCeknTde84Nq)

Unloading profiles using `aa-teardown` fixes the error

**Comment by roddhjav** [comment] 2023-01-14 13:11
Thanks, Should be fixed now.

**Closed** 2023-01-14 13:10 UTC

**Comment by abhigit23** [comment] 2023-01-14 16:57
Thanks, it's working now. Although it's still giving an error `error: could not get current working directory` despite that snapper is creating snapshots

    $ sudo pacman -S pdftk
```
warning: pdftk-3.3.3-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) pdftk-3.3.3-2

Total Installed Size:  0.98 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                               [################################] 100%
(1/1) checking package integrity                             [################################] 100%
(1/1) loading package files                                  [################################] 100%
(1/1) checking for file conflicts                            [################################] 100%
(1/1) checking available disk space                          [################################] 100%
:: Running pre-transaction hooks...
(1/1) Performing snapper pre snapshots for the following configurations...
error: could not get current working directory
==> root: 269
:: Processing package changes...
(1/1) reinstalling pdftk                                     [################################] 100%
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Generating GRUB config to let grub-btrfs detect new snapshots...
Generating grub configuration file ...
Found 50 snapshot(s)
Unmount /tmp/grub-btrfs.oaghdhhF5C .. Success
done
(3/3) Performing snapper post snapshots for the following configurations...
==> root: 270
```

Should I ignore the error? 🤔

**Comment by roddhjav** [comment] 2023-01-14 19:46
That is a feature, not a bug...

According the Arch guideline, on Archlinux, packages cannot install files under `/home/`. So I added a rule to pacman to ensure this (some package from the AUR might have rogue install script). But pacman itself get its current directory. So you will see this message when you run pacman inside `/home`. You can safely ignore the message as it not used by pacman anyway.
